# Generated by Django 2.2.2 on 2019-06-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('place', models.CharField(max_length=30)),
                ('date_of_journey', models.DateField()),
                ('contact_no', models.CharField(max_length=10)),
            ],
        ),
    ]
